config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users,
  :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  },
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup'
  }

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :cohorts
  resources :surveys
  resources :survey_responses
  resources :survey_questions
  
  resources :projects, except: [:show]
  resources :projects, only: [:show] do
    resource :survey_responses
  end

  resources :categories
  resources :categories, only: [:show] do
    resources :posts do
      resources :comments
    end
  end

  get '/dashboard', to: 'dashboard#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :redirect_if_not_logged_in, :redirect_if_no_cohort
  before_action :find_category, :find_post, :find_comments, only: [:create, :edit, :update, :destroy]
  before_action :find_comment, only: [:edit, :update, :destroy]
  
  def create
    @user = current_user

    params[:comment][:post_id] = @post.id
    params[:comment][:user_id] = @user.id

    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to category_post_path(@category, @post)
      flash[:success] = "Successfully created new comment!"
    else
      redirect_to request.referrer
      flash[:error] = "Cannot submit empty field! Please try again."
    end
  end
  
  def edit
  end
  
  def update
    if @comment.update(comment_update_params)
      redirect_to category_post_path(@category, @post)
      flash[:success] = "Successfully updated comment!"
    else
      render :edit
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to category_post_path(@category, @post)
    flash[:success] = "Successfully deleted comment."
  end

  private

  def find_comment
    @comment = Comment.find_by_id(params[:id])
  end

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def find_category
    @category = Category.find_by_id(params[:category_id])
  end

  def find_comments
    @comments = @post.comments
  end

  def comment_params
    params.require(:comment).permit(
      :content,
      :post_id,
      :user_id
    )
  end

  def comment_update_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for [category, post, comment], local: true do |f| %>
  <div class="d-flex flex-row add-comment-section mt-4 mb-4">
    <%= f.text_field :content, class: "form-control", style: "margin-right: 1rem !important", placeholder: "Add comment" %>
    <%= f.submit button_name, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-12">
            <%= render partial: "comments/comment_form", locals: { comment: @comment, post: @post, category: @category, button_name: "Comment" } %>
            <div class="headings d-flex justify-content-between align-items-center mb-3">
                <h5>Comments:</h5>
            </div>            
            <% @comments.each do |comment| %>
                <div class="card p-3 mb-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="user d-flex flex-row align-items-center">
                            <span>
                                <small class="font-weight-bold text-primary"><%= link_to comment.user.full_name, user_path(comment.user), class: "text-decoration-none" %></small>
                                <small class="font-weight-bold"><%= comment.content %></small>
                            </span>
                        </div>
                        <small><%= comment.created_at %></small>
                    </div>
                    <div class="action d-flex justify-content-between mt-2 align-items-center">
                        <div class="reply">
                            <% if is_admin? || comment.user == current_user %>
                                <small><%= link_to "Edit", edit_category_post_comment_path(@category, @post, comment) %></small>
                                <span class="dots"></span>
                                <small><%= link_to "Remove", category_post_comment_path(@category, @post, comment), method: "delete" %></small>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/comments/edit.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Edit Comment" } %>

<%= render partial: "/comments/comment_form", locals: { comment: @comment, post: @post, category: @category, button_name: "Update Comment" } %>