config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users,
  :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  },
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup'
  }

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :cohorts
  resources :surveys
  resources :survey_responses
  resources :survey_questions
  
  resources :projects, except: [:show]
  resources :projects, only: [:show] do
    resource :survey_responses
  end

  resources :categories
  resources :categories, only: [:show] do
    resources :posts do
      resources :comments
    end
  end

  get '/dashboard', to: 'dashboard#index'
end

app/models/project.rb
class Project < ApplicationRecord
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  validates :name, presence: true
  validates :phase_num, presence: true
  validates :description, presence: true
  validates :website_link, presence: true
  validates :github_link, presence: true
  validates :blog_link, presence: true
  validates :video_link, presence: true

  belongs_to :user
  has_many :survey_responses, dependent: :delete_all
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper
  helper_method :sort_direction, :sort_direction
  
  before_action :redirect_if_not_logged_in, :redirect_if_no_cohort
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_project_not_found, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_admin_or_owner, only: [:edit, :update, :destroy]

  def index
    @projects = Project.order(sort_column + " " + sort_direction)
  end

  def new
    @project = Project.new
  end

  def show
    project_report
  end

  def create
    params[:project][:user_id] = current_user.id
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project)
      flash[:success] = "Successfully created new project!"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      redirect_to project_path(@project)
      flash[:success] = "Successfully updated project!"
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
    flash[:success] = "Successfully deleted project."
  end

  private

  def find_project
    @project = Project.find_by_id(params[:id])
  end

  def redirect_if_project_not_found
    unless @project
      redirect_to projects_path
    end
  end

  def redirect_if_not_admin_or_owner
    unless @project.user == current_user
      redirect_to project_path(@project)
    end
  end

  def project_report
    @survey_count = @project.survey_responses.count
    @design_score = @project.survey_responses.calculate(:average, :design_response).to_f.round(2)
    @navigation_score = @project.survey_responses.calculate(:average, :navigation_response).to_f.round(2)
    @error_handling_score = @project.survey_responses.calculate(:average, :error_handling_response).to_f.round(2)
    @rating_score = ((@design_score + @navigation_score + @error_handling_score)/3.00).round(2)
  end

  def project_params
    params.require(:project).permit(
      :name,
      :phase_num,
      :description,
      :website_link,
      :github_link,
      :blog_link,
      :video_link,
      :user_id
    )
  end

  def sort_column
    Project.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def score_bar(score)
    (score / 5.00) * 100.00
  end
end

app/views/projects/_pform.html.erb
<%= render partial: "shared/error", locals: { model: project } %>

<%= form_with model: project, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phase_num %>
    <%= f.select :phase_num, options_for_select(["1", "2", "3", "4", "5"], project.phase_num.to_s ), { include_blank: "Select Phase" }, { class: "form-select mb-1" } %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website_link %>
    <%= f.text_field :website_link, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :github_link %>
    <%= f.text_field :github_link, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :blog_link %>
    <%= f.text_field :blog_link, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :video_link %>
    <%= f.text_field :video_link, class: "form-control" %>
  </div>
  <%= f.submit button_name, class: "btn btn-dark mt-3" %>
<% end %>

app/views/projects/edit.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Edit Project" } %>

<%= render partial: "pform", locals: { project: @project, button_name: "Update Project" } %>

app/views/projects/index.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Projects List" } %>

<table class="table table-striped">
  <tr>
    <th><%= sortable "name", "Project Name" %></th>
    <th>Created By</th>
    <th><%= sortable "phase_num", "Phase Number" %></th>
    <th>Cohort</th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project_path(project), class: "link-dark" %></td>
      <td><%= link_to project.user.full_name, project_path(project), class: "link-dark" %></td>
      <td>Phase <%= project.phase_num %></td>
      <td><%= link_to project.user.cohort.name, cohort_path(project.user.cohort), class: "link-dark" %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Create New Project", new_project_path, class: "btn btn-dark" %>

app/views/projects/new.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Create New Project" } %>

<%= render partial: "pform", locals: { project: @project, button_name: "Create Project" } %>

app/views/projects/show.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Project Info" } %>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @project.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Phase <%= @project.phase_num %></h6>
    <p class="card-text"><%= @project.description %></p>

    <%= link_to @project.website_link, class: "card-link link-dark", style: "text-decoration: none;" do %>
      <span data-feather="external-link" style="height: 15x; width: 15x;"></span>
      &nbsp;Website
    <% end %>
    <%= link_to @project.github_link, class: "card-link link-dark", style: "text-decoration: none;" do %>
      <span data-feather="github" style="height: 15x; width: 15x;"></span>
      &nbsp;GitHub
    <% end %>
    <%= link_to @project.blog_link, class: "card-link link-dark", style: "text-decoration: none;" do %>
      <span data-feather="file-text" style="height: 15x; width: 15x;"></span>
      &nbsp;Blog
    <% end %>
    <%= link_to @project.video_link, class: "card-link link-dark", style: "text-decoration: none;" do %>
      <span data-feather="video" style="height: 15x; width: 15x;"></span>
      &nbsp;Video
    <% end %>
  </div>
</div>

<div class="mt-3">
  <% if is_admin? || @project.user == current_user %>
    <%= link_to "Edit", edit_project_path(@project), class: "btn btn-sm btn-dark" %>
    <%= link_to "Delete", project_path(@project), method: "delete", class: "btn btn-sm btn-dark" %>
  <% end %>

  <%= link_to "Submit Survey", new_project_survey_responses_path(@project), class: "btn btn-sm btn-dark" unless @project.user == current_user%>
</div>

<div class="row gutters-sm mt-3">
  <div class="col mb-3">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="d-flex align-items-center mb-2">Survey Results</h5>
        <h6 class="d-flex align-items-center mb-3 text-muted">Total Surveys: <%= @survey_count %> </h6>
        <small>Design Score: <%= @design_score %> / 5.00</small>
        <div class="progress mb-3" style="height: 5px">
          <div class="progress-bar bg-primary" role="progressbar" style="width: <%= score_bar(@design_score) %>%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <small>Navigation Score: <%= @navigation_score %> / 5.00</small>
        <div class="progress mb-3" style="height: 5px">
          <div class="progress-bar bg-primary" role="progressbar" style="width: <%= score_bar(@navigation_score) %>%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <small>Error Handling Score: <%= @error_handling_score %> / 5.00</small>
        <div class="progress mb-3" style="height: 5px">
          <div class="progress-bar bg-primary" role="progressbar" style="width: <%= score_bar(@error_handling_score) %>%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <small>Overall Score: <%= @rating_score %> / 5.00</small>
        <div class="progress mb-3" style="height: 5px">
          <div class="progress-bar bg-primary" role="progressbar" style="width: <%= score_bar(@rating_score) %>%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>
  </div>
</div>