config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users,
  :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  },
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup'
  }

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :cohorts
  resources :surveys
  resources :survey_responses
  resources :survey_questions
  
  resources :projects, except: [:show]
  resources :projects, only: [:show] do
    resource :survey_responses
  end

  resources :categories
  resources :categories, only: [:show] do
    resources :posts do
      resources :comments
    end
  end

  get '/dashboard', to: 'dashboard#index'
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :survey_questions, dependent: :delete_all
  has_many :survey_responses, dependent: :delete_all

  validates :name, presence: true
  validates :phase_num, presence: true

  accepts_nested_attributes_for :survey_questions, reject_if: :all_blank
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  include SurveysHelper

  before_action :redirect_if_not_logged_in, :redirect_if_no_cohort, :redirect_if_not_admin
  before_action :find_survey, only: [:show, :edit, :update, :destroy]
  
  def index
    @surveys = Survey.order(sort_column + " " + sort_direction)
  end

  def new
    @survey = Survey.new
    @survey_question = @survey.survey_questions.build
  end

  def show
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to survey_path(@survey)
    else
      flash[:error] = @survey.errors.full_messages
      render :new
    end
  end

  def edit
  end
  
  def update
    if @survey.update(survey_update_params)
      redirect_to survey_path(@survey)
    else
      flash[:error] = @survey.errors.full_messages
      render :edit
    end
  end

  def destroy
    @survey.destroy
    redirect_to surveys_path
  end

  private

  def find_survey
    @survey = Survey.find_by_id(params[:id])
  end

  def redirect_if_not_admin
    unless is_admin?
      redirect_to dashboard_path
    end
  end

  def survey_params
    params.require(:survey).permit(
      :name,
      :phase_num,
      survey_questions_attributes: [
        :design_question, 
        :navigation_question, 
        :error_handling_question, 
        :rating
      ]
    )
  end

  def survey_update_params
    params.require(:survey).permit(
      :name,
      :phase_num,
      survey_questions_attributes: [
        :id,
        :design_question, 
        :navigation_question, 
        :error_handling_question, 
        :rating
      ]
    )
  end

  def sort_column
    Survey.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_sform.html.erb
<%= form_with model: survey, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phase_num %>
    <%= f.select :phase_num, options_for_select(["1", "2", "3", "4", "5"], survey.phase_num.to_s ), { include_blank: "Select Phase" }, { class: "form-select mb-1" } %>
  </div>

  <%= f.fields_for :survey_questions do |sq| %>
    <%= sq.hidden_field :id %>
    
    <div class="form-group">
      <%= sq.label :design_question %>
      <%= sq.text_field :design_question, class: "form-control" %>
    </div>
      
    <div class="form-group">
      <%= sq.label :navigation_question %>
      <%= sq.text_field :navigation_question, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= sq.label :error_handling_question %>
      <%= sq.text_field :error_handling_question, class: "form-control" %>
    </div>
  <% end %>
  
  <%= f.submit button_name, class: "btn btn-dark mt-3" %>
<% end %>

app/views/surveys/edit.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Edit Survey" } %>

<%= render partial: "sform", locals: { survey: @survey, button_name: "Update Survey" } %>

app/views/surveys/index.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Surveys List" } %>

<table class="table table-striped">
  <tr>
    <th><%= sortable "name" %></th>
    <th><%= sortable "phase_num", "Phase Number" %></th>
    <th><%= sortable "created_at", "Created At" %></th>
  </tr>

  <% @surveys.each do |survey| %>
    <tr>
      <td><%= link_to "#{survey.name}", survey_path(survey), class: "link-dark" %></td>
      <td>Phase <%= "#{survey.phase_num}" %></td>
      <td><%= "#{survey.created_at}" %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Create New Survey", new_survey_path, class: "btn btn-dark"  %>

app/views/surveys/new.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Create New Survey" } %>

<%= render partial: "sform", locals: { survey: @survey, button_name: "Create Survey" } %>

app/views/surveys/show.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Survey Questions" } %>

<div class="mt-2">
  <h4 class="mb-2"><%= @survey.name %></h4>

  <h6><%= @survey.survey_questions.first.design_question %></h6>
  <h6><%= @survey.survey_questions.first.navigation_question %></h6>
  <h6><%= @survey.survey_questions.first.error_handling_question %></h6>
</div>

<div class="mt-3">
  <%= link_to "Edit", edit_survey_path(@survey), class: "btn btn-sm btn-dark" %>
  <%= link_to "Delete", "#", method: "delete", class: "btn btn-sm btn-dark" %>
</div>