config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users,
  :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  },
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup'
  }

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :cohorts
  resources :surveys
  resources :survey_responses
  resources :survey_questions
  
  resources :projects, except: [:show]
  resources :projects, only: [:show] do
    resource :survey_responses
  end

  resources :categories
  resources :categories, only: [:show] do
    resources :posts do
      resources :comments
    end
  end

  get '/dashboard', to: 'dashboard#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :delete_all

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include CategoriesHelper

  before_action :redirect_if_not_logged_in, :redirect_if_no_cohort
  before_action :find_category, only: [:show, :edit, :update, :destroy]
  before_action :find_posts, only: [:show]
  before_action :redirect_if_not_admin, except: [:index, :show]
  
  def index
    @categories = Category.order(sort_column + " " + sort_direction)
  end

  def new
    @category = Category.new
  end

  def show
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
      flash[:success] = "Successfully created new category!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category)
      flash[:success] = "Successfully updated category!"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
    flash[:success] = "Successfully deleted category."
  end

  private

  def find_posts
    @posts = @category.posts.order(sort_column + " " + sort_direction)
  end

  def find_category
    @category = Category.find_by_id(params[:id])
  end

  def redirect_if_not_admin
    unless is_admin?
      redirect_to categories_path
    end
  end

  def category_params
    params.require(:category).permit(
      :name,
      :description
    )
  end

  def sort_column
    Category.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_cat_form.html.erb
<%= render partial: "shared/error", locals: { model: category } %>

<%= form_with model: category, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <%= f.submit button_name, class: "btn btn-dark mt-3" %>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Edit Category" } %>

<%= render partial: "cat_form", locals: { category: @category, button_name: "Update Category" } %>

app/views/categories/index.html.erb
<%= render partial: "/shared/header", locals: { header_name: "The Watercooler" } %>

<table class="table table-striped">
  <tr>
    <th><%= sortable "name", "Topic" %></th>
    <th>Total Posts</th>
    <th><%= sortable "created_at", "Created At" %></th>
    <% if is_admin? %>
      <th>Actions</th>
    <% end %>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category_path(category), class: "link-dark" %></td>
      <td><%= category.posts.count %></td>
      <td><%= category.created_at %></td>
      <% if is_admin? %>
        <th><%= link_to "Edit", edit_category_path(category), class: "link-dark" %> | <%= link_to "Delete", category_path(category), method: "delete", class: "link-dark" %></th>
      <% end %>
    </tr>

  <% end %>
</table>

<% if is_admin? %>  
  <%= link_to "Create New Category", new_category_path, class: "btn btn-dark"  %>
<% end %>

app/views/categories/new.html.erb
<%= render partial: "/shared/header", locals: { header_name: "Create New Category" } %>

<%= render partial: "cat_form", locals: { category: @category, button_name: "Create Category" } %>

app/views/categories/show.html.erb
<%= render partial: "/shared/header", locals: { header_name: "#{@category.name}" } %>

<div class="mt-3 mb-3">
  <p class="fst-italic"><%= @category.description %></p>
</div>

<table class="table table-striped">
  <tr>
    <th><%= sortable "title" %></th>
    <th>Total Comments</th>
    <th>Created By</th>
    <th><%= sortable "created_at", "Created At" %></th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, category_post_path(@category, post), class: "link-dark" %></td>
      <td><%= post.comments.count %></td>
      <td><%= post.user.full_name %></td>
      <td><%= post.created_at %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Create New Post", new_category_post_path(@category), class: "btn btn-dark" %>